/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws IOException {
        System.out.println("Please enter your image path");
        Scanner scanner = new Scanner(System.in);
        File bmpFile= new File(scanner.nextLine());

        BufferedImage image=ReadData.readData(bmpFile);
        System.out.println(image);

        System.out.println("Please enter your image printing path");
        File printingFile = new File(scanner.nextLine());

        System.out.println("Please enter your transformation");

        String transformation = new String(scanner.nextLine());

        //       System.out.println(Rotate180degrees.Rotate180Degrees(image));


    }
}
